name: person_linkage_case_study
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  # We use a slightly older version of R, because that
  # is what is compatible with IHME's RStudio
  - r-base=4.2
  - r-devtools
  - r-renv
  - graphviz # needed for dask visualizations
  # for building duckdb
  - cmake
  - cxx-compiler
  - ninja
  - pip
  # Python packages managed with pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - "pseudopeople[dask] @ git+https://github.com/ihmeuw/pseudopeople.git@217800e1002e03a69154819e09c44ed9455df590"
    - pyarrow
    - splink
    - jellyfish
    - rpy2
    # Distributed execution
    - pyspark==3.4.1 # NOTE: I have no idea why, but pyspark 3.5.0 (with the correct version of Spark) would hang forever on the first stage
    - dask_jobqueue
    - "bokeh!=3.0.*,>=2.4.2" # needed for dask dashboard
    - graphviz # needed for dask visualizations
    # Jupyter stuff
    - jupyterlab
    - papermill
    - ipywidgets
    - nbdime
    # For future experiments
    - snakemake
    - "ibis-framework[pandas,dask,duckdb]"
    
