data_to_use: small_sample
root_output_dir: output
conda_environment_name: person_linkage_case_study
custom_run_suffix: ''
papermill_params:
  small_sample:
    generate_pseudopeople_simulated_datasets:
      compute_engine: pandas
    generate_case_study_files:
      compute_engine: pandas
    link_datasets:
      compute_engine: pandas
      splink_engine: duckdb
    calculate_ground_truth_accuracy:
      compute_engine: pandas
  ri:
    generate_pseudopeople_simulated_datasets:
      compute_engine: dask
      num_jobs: 100
      memory_per_job: 30GB
      cpus_per_job: 5
    generate_case_study_files:
      compute_engine: dask
      num_jobs: 10
      memory_per_job: 60GB
      cpus_per_job: 2
    link_datasets:
      compute_engine: dask
      compute_engine_num_jobs: 10
      compute_engine_memory_per_job: 15GB
      compute_engine_cpus_per_job: 2
      splink_engine: spark
      spark_cpus_master: 10
      spark_memory_master: 30GB
      spark_num_workers: 50
      spark_memory_per_worker: 30GB
      spark_cpus_per_worker: 2
      spark_worker_memory_overhead_mb: 5_000
    calculate_ground_truth_accuracy:
      compute_engine: dask
      compute_engine_num_jobs: 20
      compute_engine_memory_per_job: 30GB
      compute_engine_cpus_per_job: 2
  usa:
    generate_pseudopeople_simulated_datasets:
      compute_engine: dask
      num_jobs: 100
      memory_per_job: 30GB
      cpus_per_job: 5
    generate_case_study_files:
      compute_engine: dask
      num_jobs: 50
      memory_per_job: 120GB
      cpus_per_job: 5
    link_datasets:
      compute_engine: dask
      compute_engine_num_jobs: 50
      compute_engine_memory_per_job: 120GB
      compute_engine_cpus_per_job: 2
      splink_engine: spark
      spark_cpus_master: 10
      spark_memory_master: 40GB
      spark_num_workers: 50
      spark_memory_per_worker: 120GB
      spark_cpus_per_worker: 2
      spark_worker_memory_overhead_mb: 5_000
    calculate_ground_truth_accuracy:
      compute_engine: dask
      compute_engine_num_jobs: 50
      compute_engine_memory_per_job: 120GB
      compute_engine_cpus_per_job: 2
