name: generate_simulated_data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  # Python packages managed with pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - pyarrow
    - pseudopeople
    # Technically not required, if you're not going to use notebooks
    - ipykernel
    
      
