name: generate_simulated_data_modin
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  # Python packages managed with pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - pyarrow
    - pseudopeople @ git+https://github.com/ihmeuw/pseudopeople@63606467aad4d775e19b750c8f44920a9bac3ebe
    - modin[ray,dask] @ git+https://github.com/modin-project/modin@23ebe6b35ec36dece4a99d23d41070dbf99206a2
    - dask_jobqueue
    - bokeh!=3.0.*,>=2.4.2
    # Technically not required, if you're not going to use notebooks
    - ipykernel
      
