decennial_census:
    first_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    last_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    middle_initial:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 1
    street_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    street_number:
        numeric_miswriting:
            row_noise_level: 0.1
            token_noise_level: 0.1
    unit_number:
        numeric_miswriting:
            row_noise_level: 0.1
            token_noise_level: 0.1
    zipcode:
        numeric_miswriting:
            row_noise_level: 0.1
            token_noise_level: 0.1

taxes_w2_and_1099:
    first_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    last_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    middle_initial:
        typographic:
            row_noise_level: 0.05
            token_noise_level: 1
    mailing_address_street_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    mailing_address_street_number:
        numeric_miswriting:
            row_noise_level: 0.3
            token_noise_level: 0.1
    mailing_address_unit_number:
        numeric_miswriting:
            row_noise_level: 0.3
            token_noise_level: 0.1
    mailing_address_zipcode:
        numeric_miswriting:
            row_noise_level: 0.3
            token_noise_level: 0.1

social_security:
    first_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    last_name:
        typographic:
            row_noise_level: 0.1
            token_noise_level: 0.1
    middle_initial:
        typographic:
            row_noise_level: 0.05
            token_noise_level: 1
    ssn:
        missing_data:
            row_noise_level: 0
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
            include_original_token_level: 0
        numeric_miswriting:
            row_noise_level: 0.02
            token_noise_level: 0.1